language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - ls ~/.cargo/bin/rustig || cargo install --git https://github.com/Technolution/rustig rustig
script:
  - cargo build
  - cargo test
  - cargo build --release && ~/.cargo/bin/rustig -b target/release/parse_demo