[package]
name = "tf-demo-parser"
description = "parser for tf2 demo files"
version = "0.2.5"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/demostf/parser"
exclude = [ "tests/fuzz", "data" ]

[lib]
name = "tf_demo_parser"
path = "src/lib.rs"

[[bin]]
name = "parse_demo"
path = "src/bin/main.rs"
[[bin]]

name = "loop"
path = "src/bin/loop.rs"

[dependencies]
bitbuffer = "0.8.1"
num_enum = "0.5"
num-traits = "0.2"
enumflags2 = "0.7"
snap = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
err-derive = "0.3"
parse-display = "0.5"
main_error = "0.1"
jemallocator = { version = "0.3", optional = true }
better-panic = { version = "0.2", optional = true }
no-panic = { version = "0.1", optional = true }
fnv = "1.0"

[dev-dependencies]
pretty_assertions = "0.7"
test-case = "1.0.0"
iai = "0.1"

[profile.release]
lto = true

[profile.dev]
opt-level = 2

[[bench]]
name = "iai"
harness = false
