[package]
name = "tf-demo-parser"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[lib]
name = "tf_demo_parser"

[[bin]]
name = "test"
path = "src/bin/main.rs"

[dependencies]
bitstream_reader = { version = "0.3", path = "../../bitbuffer" }
enum-primitive-derive = "0.1.2"
num-traits = "0.2"
enumflags2 = "0.5"
enumflags2_derive = "0.5"
arraydeque = "0.4"
snap = "0.2"