[package]
name = "tf-demo-parser"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[lib]
name = "tf_demo_parser"
path = "src/lib.rs"

[[bin]]
name = "parse_demo"
path = "src/bin/main.rs"

[dependencies]
bitstream_reader = { version = "0.6.3", features = ["unsafe"] }
enum-primitive-derive = "0.1"
num-traits = "0.2"
enumflags2 = "0.5"
enumflags2_derive = "0.5"
snap = "0.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
better-panic = "0.1"
err-derive = "0.1"
parse-display = "0.1"
jemallocator = "0.3"

[dev-dependencies]
pretty_assertions = "0.6"

[profile.release]
lto = true